name: Maverick-Web

on:
  push:
    branches:
    - 'master'
    - 'stable'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup yarn
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Create distribution
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          yarn install
          yarn build --report
      - name: Upload distribution artifact
        uses: actions/upload-artifact@v1
        with:
          name: maverick-web
          path: ./dist
      - name: Create distribution artifact zip
        run: cd ./dist; zip -qq -r ../maverick-web.zip .; cd ..
      - name: Publish distribution artifact (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: './maverick-web.zip'
          asset_name: 'maverick-web.zip'
          tag: ${{ github.ref }}
          overwrite: true
      - name: Commit to maverick-web-dist (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: drud/action-cross-commit@master
        with:
          source-folder: dist
          destination-repository: https://samueldudley:${{ secrets.ACCESS_TOKEN }}@github.com/goodrobots/maverick-web-dist
          destination-folder: .
          destination-branch: testing
          git-user: "samueldudley" 
          git-user-email: dudley.samuel@gmail.com
          excludes: README.md:.git:LICENSE